[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npx prisma db push --skip-generate && HOSTNAME=0.0.0.0 npm run start"
restartPolicyType = "on_failure"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
