[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npx prisma db push --skip-generate && npm run start"
restartPolicyType = "on_failure"
healthcheckPath = "/"
healthcheckTimeout = 120
